# Generated by Django 5.2.4 on 2025-07-27 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_dairy_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairyuserprofile',
            name='dairy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dairy_profile', to='mainapp.dairy'),
        ),
        migrations.AlterField(
            model_name='dairyuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dairy_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
