# Generated by Django 5.2.4 on 2025-08-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_milkcollection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollection',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
