# Generated by Django 5.2.4 on 2025-08-04 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_milkcollection_amount_milkcollection_is_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=12)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='mainapp.milkcollection')),
            ],
        ),
    ]
