# Generated by Django 5.2.4 on 2025-08-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_maindairy_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='number_of_sub_dairy',
            field=models.CharField(blank=True, null=True),
        ),
    ]
