# Generated by Django 5.2.4 on 2025-07-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_user_created_at_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairy',
            name='role',
            field=models.CharField(choices=[('Main', 'Main'), ('Branch', 'Branch')], default='Main', max_length=12),
        ),
    ]
