# Generated by Django 5.2.4 on 2025-07-27 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_dairyuserprofile_dairy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_type', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('collection_date', models.DateField(auto_now_add=True)),
                ('supplier_name', models.CharField(max_length=100)),
                ('dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.dairy')),
            ],
        ),
        migrations.CreateModel(
            name='MilkStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_type', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.dairy')),
            ],
        ),
        migrations.CreateModel(
            name='MilkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.dairy')),
            ],
        ),
    ]
