# Generated by Django 5.2.4 on 2025-07-29 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_milkcollection_milkstock_milktype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkcollection',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.dairyuserprofile'),
        ),
        migrations.AlterField(
            model_name='milkcollection',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='milkstock',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
