# Generated by Django 5.2.4 on 2025-07-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_milkcollection_supplier_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkstock',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
