# Generated by Django 5.2.4 on 2025-08-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_dairy_main_dairy'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollection',
            name='type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase')], default='Sale', max_length=12),
        ),
    ]
