# Generated by Django 5.2.4 on 2025-08-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_paymenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('plan_type', models.CharField(choices=[('Free for 7 Days', 'Free for 7 Days'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Six Months', 'Six Months'), ('Yearly', 'Yearly')], max_length=20, unique=True)),
                ('price', models.FloatField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Customer', 'Customer'), ('Manager', 'Manager')], default='Admin', max_length=12),
        ),
    ]
