# Generated by Django 5.2.4 on 2025-08-09 16:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_subscriptionplan_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindairy',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_dairy', to='mainapp.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='maindairy',
            name='expiry_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BuySubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('expiry_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_dairy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_dairy_plan', to='mainapp.maindairy')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_dairy_plan', to='mainapp.subscriptionplan')),
            ],
        ),
    ]
