# Generated by Django 5.2.4 on 2025-08-09 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_maindairy_current_plan_maindairy_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buysubscriptionplan',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='buysubscriptionplan',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='buysubscriptionplan',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buysubscriptionplan',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buysubscriptionplan',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buysubscriptionplan',
            name='main_dairy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='mainapp.maindairy'),
        ),
        migrations.AlterField(
            model_name='buysubscriptionplan',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='mainapp.subscriptionplan'),
        ),
    ]
