# Generated by Django 5.2.4 on 2025-08-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_remove_buysubscriptionplan_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindairy',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
